'use client';

import React, { useState, useEffect } from 'react';
import { callAIAgent } from '@/lib/aiAgent';
import Header from './sections/Header';
import HeroInput from './sections/HeroInput';
import ResultsSection from './sections/ResultsSection';
import HistorySidebar from './sections/HistorySidebar';

const AGENT_ID = '69ec53210263199051be340c';

const SAMPLE_DATA = {
  company_name: 'Tata Consultancy Services (TCS)',
  hypothesis: 'TCS will outperform due to strong demand in digital transformation and cloud migration services across global enterprises.',
  fundamentals_summary: '**Revenue Growth:** TCS reported Q3 FY25 revenue of Rs 63,973 crore, up 5.6% YoY. **Operating Margin:** EBIT margin at 24.5%, within the target band. **Order Book:** TCV of $8.6B in Q3, indicating strong demand pipeline. **Cash Position:** Free cash flow conversion at 107% of net income.',
  sentiment_summary: 'Overall market sentiment is cautiously optimistic. The IT sector faces near-term headwinds from client spending deferrals, but the medium-term outlook remains positive driven by AI and cloud adoption.',
  confirmations: [
    'Digital transformation spending continues to accelerate globally, with enterprises prioritizing cloud migration',
    'TCS reported strong total contract value (TCV) of $8.6B in Q3, demonstrating robust demand',
    'Operating margins remain healthy at 24.5%, showing operational discipline',
    'Strong free cash flow generation supports dividend payouts and buybacks',
  ],
  contradictions: [
    'Client spending deferrals in BFSI segment may slow near-term revenue growth',
    'Rising competition from AI-native companies could pressure pricing power',
    'Visa restrictions and immigration policy changes pose execution risks',
  ],
  confidence_score: 72,
  confidence_rationale: 'The hypothesis is largely supported by strong fundamentals and a healthy deal pipeline. However, near-term macroeconomic headwinds and competitive pressures from AI-native firms introduce moderate uncertainty.',
  key_numbers: '- **Revenue:** Rs 63,973 Cr (Q3 FY25)\n- **EBIT Margin:** 24.5%\n- **TCV:** $8.6B\n- **Employee Count:** 601,546\n- **Attrition Rate:** 12.3%\n- **FCF Conversion:** 107%\n- **P/E Ratio:** 28.4x',
  strengths: [
    'Market-leading position in IT services globally',
    'Diversified portfolio across verticals and geographies',
    'Strong operational discipline with consistent margin delivery',
    'Robust deal pipeline with large transformational deals',
  ],
  concerns: [
    'Slower discretionary spending in key markets',
    'Generative AI could disrupt traditional services revenue',
    'Currency headwinds impacting reported growth',
    'Elevated subcontractor costs in key markets',
  ],
  overall_sentiment: 'CAUTIOUSLY BULLISH',
  bullish_drivers: [
    'AI and GenAI service demand creating new revenue streams',
    'Cloud migration deals accelerating in manufacturing and retail',
    'Strong balance sheet enables strategic M&A',
  ],
  bearish_drivers: [
    'Macro uncertainty in US and European markets',
    'Wage inflation pressures in India',
    'Potential AI-driven disruption to traditional services model',
  ],
  news_breakdown: [
    { title: 'TCS wins $2B deal with major European bank for cloud transformation', sentiment: 'BULLISH', hypothesis_relevant: true, summary: 'Significant win validates the digital transformation thesis and demonstrates TCS ability to capture large deals.' },
    { title: 'IT sector faces headwinds as clients defer discretionary spending', sentiment: 'BEARISH', hypothesis_relevant: true, summary: 'Near-term spending deferrals could slow growth, contradicting immediate outperformance expectations.' },
    { title: 'TCS expands AI practice with 100+ GenAI engagements', sentiment: 'BULLISH', hypothesis_relevant: true, summary: 'Growing AI capabilities position TCS well for next-gen demand.' },
    { title: 'US visa policy changes could impact Indian IT companies', sentiment: 'BEARISH', hypothesis_relevant: false, summary: 'Regulatory risks remain an overhang for the sector.' },
  ],
  disclaimer: 'This analysis is generated by AI for educational purposes only. It does not constitute investment advice. Always consult a qualified financial advisor before making investment decisions.',
};

interface AnalysisData {
  company_name?: string;
  hypothesis?: string;
  fundamentals_summary?: string;
  sentiment_summary?: string;
  confirmations?: string[];
  contradictions?: string[];
  confidence_score?: number;
  confidence_rationale?: string;
  key_numbers?: string;
  strengths?: string[];
  concerns?: string[];
  overall_sentiment?: string;
  bullish_drivers?: string[];
  bearish_drivers?: string[];
  news_breakdown?: Array<{ title?: string; sentiment?: string; hypothesis_relevant?: boolean; summary?: string }>;
  disclaimer?: string;
}

interface SessionAnalysis extends AnalysisData {
  id: string;
  createdAt: string;
}

class ErrorBoundary extends React.Component<
  { children: React.ReactNode },
  { hasError: boolean; error: string }
> {
  constructor(props: { children: React.ReactNode }) {
    super(props);
    this.state = { hasError: false, error: '' };
  }
  static getDerivedStateFromError(error: Error) {
    return { hasError: true, error: error.message };
  }
  render() {
    if (this.state.hasError) {
      return (
        <div className="min-h-screen flex items-center justify-center" style={{ backgroundColor: 'var(--bg)', color: 'var(--text)' }}>
          <div className="text-center p-8 max-w-md">
            <h2 className="font-serif text-xl font-semibold mb-2">Something went wrong</h2>
            <p className="text-sm mb-4" style={{ color: 'var(--text-dim)' }}>{this.state.error}</p>
            <button
              onClick={() => this.setState({ hasError: false, error: '' })}
              className="px-6 py-3 text-sm font-semibold"
              style={{ backgroundColor: 'var(--accent)', color: 'var(--bg)', borderRadius: '4px' }}
            >
              Try again
            </button>
          </div>
        </div>
      );
    }
    return this.props.children;
  }
}

let nextId = 1;

export default function Page() {
  const [companyName, setCompanyName] = useState('');
  const [hypothesis, setHypothesis] = useState('');
  const [loading, setLoading] = useState(false);
  const [currentStep, setCurrentStep] = useState(0);
  const [analysisData, setAnalysisData] = useState<AnalysisData | null>(null);
  const [error, setError] = useState('');
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [analyses, setAnalyses] = useState<SessionAnalysis[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [useSample, setUseSample] = useState(false);
  const [activeAgentId, setActiveAgentId] = useState<string | null>(null);

  useEffect(() => {
    if (useSample) {
      setCompanyName('TCS');
      setHypothesis('I think TCS will outperform due to strong demand in digital transformation and cloud migration services.');
      setAnalysisData(SAMPLE_DATA);
    } else {
      setCompanyName('');
      setHypothesis('');
      setAnalysisData(null);
      setSelectedId(null);
    }
  }, [useSample]);

  const handleAnalyze = async () => {
    if (!companyName.trim() || !hypothesis.trim()) return;
    setLoading(true);
    setError('');
    setAnalysisData(null);
    setCurrentStep(0);
    setActiveAgentId(AGENT_ID);

    const stepInterval = setInterval(() => {
      setCurrentStep((prev) => (prev < 3 ? prev + 1 : prev));
    }, 3000);

    try {
      const result = await callAIAgent(
        `Company: ${companyName.trim()}\nHypothesis: ${hypothesis.trim()}`,
        AGENT_ID
      );

      clearInterval(stepInterval);
      setCurrentStep(4);

      if (result.success) {
        const data = result?.response?.result ?? result?.response ?? null;
        if (data && typeof data === 'object') {
          setAnalysisData(data as AnalysisData);
          const newEntry: SessionAnalysis = {
            ...(data as AnalysisData),
            id: String(nextId++),
            company_name: data.company_name ?? companyName,
            hypothesis: data.hypothesis ?? hypothesis,
            createdAt: new Date().toISOString(),
          };
          setAnalyses((prev) => [newEntry, ...prev]);
          setSelectedId(newEntry.id);
        } else {
          setError('Received an unexpected response format.');
        }
      } else {
        setError('Analysis failed. Please try again.');
      }
    } catch (e: any) {
      clearInterval(stepInterval);
      setError(e?.message ?? 'An error occurred during analysis.');
    } finally {
      setLoading(false);
      setActiveAgentId(null);
    }
  };

  const handleSelectAnalysis = (analysis: any) => {
    setSelectedId(analysis.id);
    setCompanyName(analysis.company_name ?? '');
    setHypothesis(analysis.hypothesis ?? '');
    setAnalysisData(analysis);
    setUseSample(false);
  };

  return (
    <ErrorBoundary>
      <div className="min-h-screen" style={{ backgroundColor: 'var(--bg)', color: 'var(--text)' }}>
        <Header onToggleSidebar={() => setSidebarOpen(!sidebarOpen)} />
        <div className="flex" style={{ height: 'calc(100vh - 64px)' }}>
          <HistorySidebar
            open={sidebarOpen}
            onClose={() => setSidebarOpen(false)}
            analyses={analyses}
            loading={false}
            onSelect={handleSelectAnalysis}
            selectedId={selectedId}
          />
          <main className="flex-1 overflow-y-auto">
            <HeroInput
              companyName={companyName}
              setCompanyName={setCompanyName}
              hypothesis={hypothesis}
              setHypothesis={setHypothesis}
              loading={loading}
              currentStep={currentStep}
              onAnalyze={handleAnalyze}
              useSample={useSample}
              setUseSample={setUseSample}
            />

            {error && (
              <div className="max-w-[700px] mx-auto px-4 mb-6">
                <div className="p-4" style={{ border: '1px solid var(--loss)', backgroundColor: 'rgba(200, 80, 80, 0.05)' }}>
                  <p className="text-sm" style={{ color: 'var(--loss)' }}>{error}</p>
                </div>
              </div>
            )}

            <ResultsSection data={analysisData} />

            {/* Agent Status */}
            <div className="max-w-[700px] mx-auto px-4 pb-8">
              <div className="p-6" style={{ border: '1px solid var(--rule)', backgroundColor: 'var(--surface)' }}>
                <p className="font-mono text-xs tracking-widest uppercase mb-2" style={{ color: 'var(--text-dim)' }}>
                  Agent Status
                </p>
                <div className="flex items-center gap-3">
                  <div
                    className={`w-2 h-2 ${activeAgentId ? 'animate-pulse' : ''}`}
                    style={{
                      borderRadius: '50%',
                      backgroundColor: activeAgentId ? 'var(--gain)' : 'var(--text-muted)',
                    }}
                  />
                  <span className="font-mono text-xs tracking-wide" style={{ color: 'var(--text-dim)' }}>
                    Research Orchestrator
                  </span>
                  <span className="font-mono text-xs" style={{ color: 'var(--text-muted)' }}>
                    {activeAgentId ? 'Processing...' : 'Idle'}
                  </span>
                </div>
                <p className="text-xs mt-2 font-sans" style={{ color: 'var(--text-muted)' }}>
                  Coordinates Fundamentals Analyst, Sentiment Analyst, and Synthesis sub-agents.
                </p>
              </div>
            </div>

            {/* Footer disclaimer */}
            <footer className="py-4 px-6 text-center" style={{ borderTop: '1px solid var(--rule)' }}>
              <p className="font-sans text-xs tracking-wider" style={{ color: 'var(--text-muted)' }}>
                Not investment advice. For educational purposes only.
              </p>
            </footer>
          </main>
        </div>
      </div>
    </ErrorBoundary>
  );
}
